// Static placeholder photos shipped in /public/placeholder (generated by scripts/make-fixtures.mjs).
// Used when the database has nothing to show (AC-HOME-01 fallback, PD-14 service cards).
import type { CategorySlug } from "../../content/site";
import { site } from "../../content/site";
import placeholders from "./placeholders.json";
import type { PublicPhoto } from "./types";

export const PLACEHOLDER_BASE = "/placeholder";

export function placeholderPhoto(id: string, alt: string = site.hero.placeholderAlt): PublicPhoto {
  const ph = placeholders.find((p) => p.id === id) ?? placeholders[0]!;
  return {
    id: `placeholder-${ph.id}`,
    mediaId: ph.id,
    width: ph.width,
    height: ph.height,
    alt,
    lqip: ph.lqip,
    base: PLACEHOLDER_BASE,
  };
}

const CATEGORY_FALLBACK: Record<CategorySlug, string> = {
  vjencanja: "ph-01",
  eventi: "ph-11",
  portreti: "ph-02",
  "iz-zraka": "ph-03",
};

export const categoryFallback = (slug: CategorySlug): PublicPhoto => placeholderPhoto(CATEGORY_FALLBACK[slug]);
